### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers'

### ISSUE THREAD

**Issue by seashell123** [kvablack/LLaVA-server#2]
When I run `gunicorn "app:create_app()"`, I get the following output:

```
[2023-07-13 18:43:26 -0700] [3134595] [INFO] Starting gunicorn 20.0.4
[2023-07-13 18:43:26 -0700] [3134595] [INFO] Listening at: http://127.0.0.1:8085 (3134595)
[2023-07-13 18:43:26 -0700] [3134595] [INFO] Using worker: sync
[2023-07-13 18:43:26 -0700] [3134597] [INFO] Booting worker with pid: 3134597
[2023-07-13 18:43:26 -0700] [3134597] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 383, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/mguo/workspace/third_party/kvablack/LLaVA-server/app.py", line 5, in <module>
    from llava_server.llava import load_llava
  File "/data/mguo/workspace/third_party/kvablack/LLaVA-server/llava_server/llava.py", line 3, in <module>
    from transformers import AutoTokenizer, AutoModelForCausalLM
ModuleNotFoundError: No module named 'transformers'
[2023-07-13 18:43:26 -0700] [3134597] [INFO] Worker exiting (pid: 3134597)
[2023-07-13 18:43:26 -0700] [3134595] [INFO] Shutting down: Master
[2023-07-13 18:43:26 -0700] [3134595] [INFO] Reason: Worker failed to boot.
```

I tried `pip install transformers` but that didn't fix the issue. Maybe because I'm not familiar with `gunicorn` -- do you know if I should be doing something different to install the `transformers` package? Or is there more generally a set of setup/installation instructions I should be running? I noticed the README didn't have any.

**Comment by kvablack** [comment]
I have no idea why this would be happening -- gunicorn should be using whatever Python environment you have activated. Can you try starting the debugging server using `flask run`?

**Comment by michguo** [comment]
This is what I get:

```
(LLaVA-server) <USER>@<HOSTNAME>:<PATH_TO_REPO>/LLaVA-server$ flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/data/<USER>/workspace/third_party/kvablack/LLaVA-server/app.py", line 5, in <module>
    from llava_server.llava import load_llava
  File "/data/<USER>/workspace/third_party/kvablack/LLaVA-server/llava_server/llava.py", line 3, in <module>
    from transformers import AutoTokenizer, AutoModelForCausalLM
ModuleNotFoundError: No module named 'transformers'
```

Should I be using a particular python environment?

**Comment by seashell123** [comment]
This is what I get:

```
(LLaVA-server) <USER>@<HOSTNAME>:<PATH_TO_REPO>/LLaVA-server$ flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/data/<USER>/workspace/third_party/kvablack/LLaVA-server/app.py", line 5, in <module>
    from llava_server.llava import load_llava
  File "/data/<USER>/workspace/third_party/kvablack/LLaVA-server/llava_server/llava.py", line 3, in <module>
    from transformers import AutoTokenizer, AutoModelForCausalLM
ModuleNotFoundError: No module named 'transformers'
```

Should I be using a particular python environment?

**Comment by kvablack** [comment]
Are you absolutely sure you have transformers installed in your current environment? If running `python -c "import transformers"` works, then `flask run` should work.

**Comment by seashell123** [comment]
Looks like `transformers` is installed:

```
(ddpo-pytorch) LLaVA-server$ python -c "import transformers"
(ddpo-pytorch) LLaVA-server$ python
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import transformers
>>> 
KeyboardInterrupt
>>> 
(ddpo-pytorch) LLaVA-server$ flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/data/<USER>/workspace/third_party/kvablack/LLaVA-server/app.py", line 5, in <module>
    from llava_server.llava import load_llava
  File "/data/<USER>/workspace/third_party/kvablack/LLaVA-server/llava_server/llava.py", line 3, in <module>
    from transformers import AutoTokenizer, AutoModelForCausalLM
ModuleNotFoundError: No module named 'transformers'
```

**Comment by kvablack** [comment]
Definitely seems like flask is using the wrong Python interpreter. All I can tell you is that I'm using Miniconda and everyting works as expected; you'll have to debug the rest yourself, sorry.
